"city","country"
"A Corua (La Corua)","Afghanistan"
"Abha","Algeria"
"Abu Dhabi","American Samoa"
"Acua","Angola"
"Adana","Anguilla"
"Addis Abeba","Argentina"
"Aden","Armenia"
"Adoni","Australia"
"Ahmadnagar","Austria"
"Akishima","Azerbaijan"
"Akron","Bahrain"
"al-Ayn","Bangladesh"
"al-Hawiya","Belarus"
"al-Manama","Bolivia"
"al-Qadarif","Brazil"
"al-Qatif","Brunei"
"Alessandria","Bulgaria"
"Allappuzha (Alleppey)","Cambodia"
"Allende","Cameroon"
"Almirante Brown","Canada"
"Alvorada","Chad"
"Ambattur","Chile"
"Amersfoort","China"
"Amroha","Colombia"
"Angra dos Reis","Congo, The Democratic Republic of the"
"Anpolis","Czech Republic"
"Antofagasta","Dominican Republic"
"Aparecida de Goinia","Ecuador"
"Apeldoorn","Egypt"
"Araatuba","Estonia"
"Arak","Ethiopia"
"Arecibo","Faroe Islands"
"Arlington","Finland"
"Ashdod","France"
"Ashgabat","French Guiana"
"Ashqelon","French Polynesia"
"Asuncin","Gambia"
"Athenai","Germany"
"Atinsk","Greece"
"Atlixco","Greenland"
"Augusta-Richmond County","Holy See (Vatican City State)"
"Aurora","Hong Kong"
"Avellaneda","Hungary"
"Bag","India"
"Baha Blanca","Indonesia"
"Baicheng","Iran"
"Baiyin","Iraq"
"Baku","Israel"
"Balaiha","Italy"
"Balikesir","Japan"
"Balurghat","Kazakstan"
"Bamenda","Kenya"
"Bandar Seri Begawan","Kuwait"
"Banjul","Latvia"
"Barcelona","Liechtenstein"
"Basel","Lithuania"
"Bat Yam","Madagascar"
"Batman","Malawi"
"Batna","Malaysia"
"Battambang","Mexico"
"Baybay","Moldova"
"Bayugan","Morocco"
"Bchar","Mozambique"
"Beira","Myanmar"
"Bellevue","Nauru"
"Belm","Nepal"
"Benguela","Netherlands"
"Beni-Mellal","New Zealand"
"Benin City","Nigeria"
"Bergamo","North Korea"
"Berhampore (Baharampur)","Oman"
"Bern","Pakistan"
"Bhavnagar","Paraguay"
"Bhilwara","Peru"
"Bhimavaram","Philippines"
"Bhopal","Poland"
"Bhusawal","Puerto Rico"
"Bijapur","Romania"
"Bilbays","Runion"
"Binzhou","Russian Federation"
"Birgunj","Saint Vincent and the Grenadines"
"Bislig","Saudi Arabia"
"Blumenau","Senegal"
"Boa Vista","Slovakia"
"Boksburg","South Africa"
"Botosani","South Korea"
"Botshabelo","Spain"
"Bradford","Sri Lanka"
"Braslia","Sudan"
"Bratislava","Sweden"
"Brescia","Switzerland"
"Brest","Taiwan"
"Brindisi","Tanzania"
"Brockton","Thailand"
"Bucuresti","Tonga"
"Buenaventura","Tunisia"
"Bydgoszcz","Turkey"
"Cabuyao","Turkmenistan"
"Callao","Tuvalu"
"Cam Ranh","Ukraine"
"Cape Coral","United Arab Emirates"
"Caracas","United Kingdom"
"Carmen","United States"
"Cavite","Venezuela"
"Cayenne","Vietnam"
"Celaya","Virgin Islands, U.S."
"Chandrapur","Yemen"
"Changhwa","Yugoslavia"
"Changzhou","Zambia"
